### ISSUE TITLE
1MB device not recognized

### ISSUE THREAD

**Issue by lmwilco1** [sosandroid/FRAM_MB85RC_I2C#13]
I have a Fijitsu MB85RC1MT device soldered to the Adafruit board. The checkDevice code fails, it calls getDeviceIDs and the FRAM is identified correctly but the maxaddress is set to  65536 but the maxadress variable is a uint16_t so the value is actually set to 0 which results in checkDevice failing. In order to get it to work I changed the #define MAXADDRESS_1024 65536 to 65535. THe 512 device probably has the same issue.

**Comment by sosandroid** [comment]
Thanks for the feedback. I'll fix asap

**Comment by sosandroid** [comment]
Fixed
