### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by beckejc** [sosandroid/FRAM_MB85RC_I2C#16]
This might be correct, but the use of '6' twice looks suspicious:

define ERROR_6 6 // Unused
#define ERROR_7 6 // Fram chip unidentified
#define ERROR_8 8 // Number of bytes asked 

If the value for ERROR_7 really is 6 please ignore

**Comment by sosandroid** [comment]
To be fixed !
This a real typo

**Comment by sosandroid** [comment]
Fixed

**Comment by beckejc** [comment]
Nice.  Thanks for the great library.
