### ISSUE TITLE
add an example for working with 1Mbit Devices ?

### ISSUE THREAD

**Issue by BlackBrix** [sosandroid/FRAM_MB85RC_I2C#17]
it is stated:

>1M devices are in fact managed as 2 512 devices from lib point of view > create 2 instances of the object with each a differnt address

is it possible to add example code for that, just to show how to do it the right way ?

------

is it planned to overcome this limitation for 1Mbit (or greater) devices in future, 
so that it is not needed anymore to create 2 instances,
but everything that is needed (special addressing and so on) is done internally within the library already ?

**Comment by sosandroid** [comment]
To add an exemple 
`#include <Wire.h>`
`#include <FRAM_MB85RC_I2C.h>`
`FRAM_MB85RC_I2C mymemory_1sthalf;`
`FRAM_MB85RC_I2C mymemory_2ndhalf;`
`mymemory_1sthalf.begin();`
`mymemory_2ndhalf.begin();`

For the rest of your question, this is possible to manage natively the 1M devices from the lib. You'll need to change the memory addressing to `uint32_t` and adapt the `I2CAddressAdapt()` method
Not sure of the behavior when reading or writing 2 bytes data starting at the last location of the 1st memory page.
