### ISSUE TITLE
FM24V05-G

### ISSUE THREAD

**Issue by bobybobybob** [sosandroid/FRAM_MB85RC_I2C#18]
FM24V05

Starting...
....... .......
FRAM Device IDs
Manufacturer 0xD5A
ProductID 0xC69
Density code 0xC

Starting...
FRAM_MB85RC_I2C object created
I2C device address 0x50
WP pin number 13
Write protect management: false
Memory Chip NOT FOUND
...... ...... ......

Starting...
FRAM_MB85RC_I2C object created
I2C device address 0x50
WP pin number 13
Write protect management: false
Memory Chip NOT FOUND
...... ...... ......
Data_0: true
Data_1: 1.3574999570
Data_2: 314159
Data_3: 142
Data_4: 0x50
...... ...... ......
Init Done - array loaded
...... ...... ......
Write failed
...... ...... ......
Read failed
...... ...... ......
Data_0: false
Data_1: 0.0000000000
Data_2: 0
Data_3: 0
Data_4: 0x0
...... ...... ......
Read Write test done - check data if successfull
...... ...... ......

**Comment by sosandroid** [comment]
Please share your code. It seems you did not initiate properly the object to match your device.

**Comment by bobybobybob** [comment]
I use the example Demos from your Library.

**Comment by sosandroid** [comment]
Thanks for your help.

Obviously, the chip you used does not match to product IDs of the Cypress datasheet.

As consequence, the library is considering the chip not found. This is a normal behaviour.

You should try to switch to manual mode as the lib allows you to do so.

**Comment by bobybobybob** [comment]
https://aliexpress.com/item/Freies-Schiff-XTR115UA-AO4422-AP4502GM-EN25F40-100GCP-EPCS4SI8N-EPCS4N-FA5518-FM24V05-G-Fm24v10-gtr-IRF7103Q-IRF7324/32835241173.html

There i have buy two. Very sad that there are Fake one...

**Comment by sosandroid** [comment]
Sorry for that.
Just try to address it in manual mode. Maybe fake but working

**Comment by sosandroid** [comment]
If same issue than #18 please try manual mode by setting density manually

**Comment by sosandroid** [comment]
No feedback, closing the issue
