### ISSUE TITLE
FM24C64-G not recognized

### ISSUE THREAD

**Issue by mattogodoy** [sosandroid/FRAM_MB85RC_I2C#19]
Hi!

I just got a few **FM24C64-G** chips from AliExpress:
https://www.aliexpress.com/item/1PCS-Fm24c64-g-fm24c64-24c64b-24C64-G-SOP8/32832467105.html

According to its datasheet (http://www.farnell.com/datasheets/305351.pdf), the pinout is the exact same as an EEPROM, so I wired it to an Arduino UNO following this diagram:
http://www.connduino.com/sites/default/files/pictures/programming_eeprom/EEPROM%20connect_bb.png

The problem is that the FRAM is not recognized by the library.
When I run *FRAM_I2C_readIDs.ino* I get:

```
Starting...
....... .......
FRAM Device IDs
Manufacturer 0xFFF
ProductID 0xFFF
Density code 0xF
...... ...... ......
```

When I run *FRAM_I2C_simple_write_read.ino* I get:

```
Starting...
FRAM_MB85RC_I2C object created
I2C device address 0x50
WP pin number 13
Write protect management: false
Memory Chip NOT FOUND
...... ...... ......
1st test
Writing at location 0x25
Writing...
Reading...
Written value 0xBE
Read value 0x0
Write Byte test : NOT OK
.... ....
Manufacturer 0xFFF
DensityCode 0xF
Density 0
```

The strange part is that I have tested writing to the module as if it were an external EEPROM memory and it works!
This is the code I tested: https://bitbucket.org/Electricks/arduiono_sketches/src/d4a242e5b1cdebb4c38a5d93fbd5d17411abe3c4/EEPROM/EEPROM.ino

Any ideas?
Thanks!

**Comment by sosandroid** [comment]
The only way to move forward is using the manual mode scketch

**Comment by bobybobybob** [comment]
same with FM24CL64

**Comment by sosandroid** [comment]
No feedback with manual mode scketch tests.
=> closed
