### ISSUE TITLE
Emulation of Arduino EEPROM library

### ISSUE THREAD

**Issue by trlafleur** [sosandroid/FRAM_MB85RC_I2C#26]
Nice package, works great but would be nice to have it also emulate the Arduino EEPROM library, this would make it easy just to replace it with this package with an external FRAM without any modification...

just a thought...

**Comment by sosandroid** [comment]
Hi,

Thanks for the feedback and idea.
At this time I have no plan yet to make Eeprom emulation from this lib.
However, PRs are welcome
