### ISSUE TITLE
Problem with TimerOne

### ISSUE THREAD

**Issue by EdHayes3** [sosandroid/FRAM_MB85RC_I2C#28]
When I use this with TimerOne I get serial output like: 

![image](https://user-images.githubusercontent.com/74882458/126027370-1113d25a-d7bd-4247-86ba-7fe52c846c86.png)

Seems the two are incompatible with each other.

When I don't include the FRAM initialization, I have no problems.

**Comment by EdHayes3** [comment]
...This may have been a memory issue...

**Comment by sosandroid** [comment]
Not sure I can help.
Does you terminal properly set regarding UART communication ?

**Comment by EdHayes3** [comment]
I confirmed, my fault, MCU Memory issue. Needed to clean up my code to reduce memory consumption.
